spring:
  data:
    mongodb:
      port: ${MONGODB_POST:27017}
      username: ${MONGODB_USER:root}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
      host: ${MONGODB_HOST}
      database: ${MONGODB_DATABASE}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_POST:6379}
      password: ${REDIS_PASSWORD}
security:
  jwt:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
#logging:
#  level:
#    org:
#      springframework:
#        security=TRACE: