apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth-svc
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service
          env:
            - name: MONGODB_HOST
              value: mongodb.dev.svc.cluster.local
            - name: MONGODB_USER
              value: root
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
            - name: MONGODB_POST
              value: "27017"
            - name: MONGODB_DATABASE
              value: dbmain
            - name: REDIS_HOST
              value: redis-master-0.redis-headless.dev.svc.cluster.local
            - name: REDIS_POST
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: JWT_SECRET
              value: 72764ebeb874350a0a67d0bf914eff58660a0e8d36c5fa26c36f6e12a1f55865
